### ISSUE TITLE
quotation marks are showing up as ?

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/ASL-DAI#127]
<img width="734" alt="Screen Shot 2019-07-02 at 8 51 58 AM" src="https://user-images.githubusercontent.com/13629122/60514104-c11e3f80-9ca6-11e9-896c-d22f3a318ca4.png">

**Comment by cneidle** [comment]
The other " look ok.  So I will check to see if the ? is in the annotated version...  (when I can access the VPN next; Carey is working now).  Will report back here.  thanks.

**Comment by cneidle** [comment]
I checked and the SignStream version is fine - has quotation marks.  Not sure why only this example is a problem.  I retyped the quotation marks.  We can see if the problem goes away on the next import...

**Comment by cneidle** [comment]
There were some other examples of this problem, with no apparent cause.  The text is seemingly correct in the SignStream files.  I retyped the quotation marks, in case that makes a difference...

<img width="151" alt="Screen Shot 2019-07-03 at 5 49 55 AM" src="https://user-images.githubusercontent.com/13629122/60583707-7c071580-9d59-11e9-9a7e-9e253a270465.png">

**Comment by cneidle** [comment]
There are several other examples like this among the classifiers...

**Comment by cneidle** [comment]
There are problems all over with quotation marks.  I am replacing them where I see the problems, but I don't know if it will even help.  I suspect that the problem is that there are special characters ("smart quotes") that maybe getting into these files for some reason.  Might be a good idea to do a global replace of smart quotes with regular quotes as a final step in entering data into the database...  Just a thought - obviously you are the expert :-)

**Comment by kwasiopoku** [comment]
mysql> select text from Sign where text like '%forget%'
    -> ;
+--------------------+
| text               |
+--------------------+
| (1h)5"forget it"   |
| (1h)5"forget it"   |
| (1h)5"forget it"   |
| (1h)5"forget it"   |
| (1h)5"forget it"   |
| (1h)5”forget it"   |
| (1h)5”forget it"   |
| (1h)5”forget it"   |
| 5"forget it"       |
| 5"forget it"       |
| 5"forget it"       |
| 5"forget it"       |
| 5"forget it"       |
| 5"forget it"       |
| 5"forget it"       |
| 5"forget it"       |
| FORGET             |
| FORGET-IT          |
| FORGET-IT          |
| FORGET-IT          |

**Comment by kwasiopoku** [comment]
Fixed

**Comment by cneidle** [comment]
merge with #339

**Comment by cneidle** [comment]
This is also still a problem with a few listings in the Sign Bank where ? replaces a special character like " , e.g.

<img width="117" alt="Screen Shot 2022-09-02 at 10 24 39 AM" src="https://user-images.githubusercontent.com/13629122/188171358-e740444f-bb62-4bf1-82f8-bcf08dbf4837.png">

<img width="253" alt="Screen Shot 2022-09-02 at 10 25 10 AM" src="https://user-images.githubusercontent.com/13629122/188171360-b8d5fd64-67c1-441e-a6f1-a661401db53c.png">

**Comment by kwasiopoku** [comment]
These have been fixed on dev1.cs

**Comment by cneidle** [comment]
great!  thank you

**Comment by cneidle** [comment]
thanks!
