### ISSUE TITLE
Problem from this morning is recurring - sign+ fails to be classified, but listed with 0 occurrences

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/ASL-DAI#130]
I tried to classify FIREWORKS_2 (with various numbers of plusses) as a variant under FIREWORKS.

It fails to strip the +  ---  exactly as was occurring earlier.

<img width="475" alt="Screen Shot 2019-07-02 at 11 33 13 PM" src="https://user-images.githubusercontent.com/13629122/60561585-06338780-9d22-11e9-94fd-d8591b7c1660.png">

**Comment by cneidle** [comment]
Another instance of the same problem:  I tried to classify
two instances of "NEGLECT" that had plusses at the end...

<img width="174" alt="Screen Shot 2019-07-04 at 12 54 28 AM" src="https://user-images.githubusercontent.com/13629122/60640695-61cf4500-9df6-11e9-9430-059367952824.png">

**Comment by cneidle** [comment]
Attempt to classify this sign also did not work:

<img width="1019" alt="Screen Shot 2019-07-04 at 1 18 03 AM" src="https://user-images.githubusercontent.com/13629122/60641495-fb4c2600-9df9-11e9-9551-43ba19c92f2c.png">

**Comment by cneidle** [comment]
This is a bit different, but I am also unable to classify this:

<img width="1298" alt="Screen Shot 2019-07-04 at 7 11 49 AM" src="https://user-images.githubusercontent.com/13629122/60662727-2b5fed00-9e2b-11e9-810d-691e24bdb64f.png">

**Comment by kwasiopoku** [comment]
Fixed

**Comment by cneidle** [comment]
THANKS for all you are doing.

This still does not seem to be fixed, however:

**Comment by kwasiopoku** [comment]
Fixed

**Comment by cneidle** [comment]
I tried to add THANK-YOU+.

The same problem recurred:  A variant entry including the + was recorded with 0 occurrences, and the item remained in the list to be classified.

<img width="701" alt="Screen Shot 2019-07-24 at 10 06 32 AM" src="https://user-images.githubusercontent.com/13629122/61800462-0e4f8600-adfb-11e9-9482-c152e53173d3.png">

WHen I tried again, this time manually deleting the + from the variant label, that worked, but
the previous (0) entry remains:

<img width="698" alt="Screen Shot 2019-07-24 at 10 07 35 AM" src="https://user-images.githubusercontent.com/13629122/61800494-21625600-adfb-11e9-8e6c-cd018d7e7153.png">

**Comment by cneidle** [comment]
Here is another case where a (0) occurrence is showing up:

<img width="122" alt="Screen Shot 2019-07-24 at 11 05 24 AM" src="https://user-images.githubusercontent.com/13629122/61805631-1eb82e80-ae04-11e9-8ebf-efb55ac62740.png">

**Comment by cneidle** [comment]
This is still a problem:

<img width="509" alt="Screen Shot 2019-08-06 at 6 04 55 PM" src="https://user-images.githubusercontent.com/13629122/62580747-f8b77300-b874-11e9-9328-7a288bd4696d.png">

**Comment by cneidle** [comment]
A related problem?

<img width="514" alt="Screen Shot 2019-08-06 at 6 08 42 PM" src="https://user-images.githubusercontent.com/13629122/62580840-52b83880-b875-11e9-8a8d-033cae10b446.png">

**Comment by cneidle** [comment]
Same problem again:

<img width="1391" alt="Screen Shot 2019-08-06 at 6 12 12 PM" src="https://user-images.githubusercontent.com/13629122/62581076-0a4d4a80-b876-11e9-90dc-de8670c3274f.png">

<img width="602" alt="Screen Shot 2019-08-06 at 6 13 51 PM" src="https://user-images.githubusercontent.com/13629122/62581082-0e796800-b876-11e9-8d53-7aad0aa27fe2.png">


*OOPS* - This one actually needs a correction. So for now should be deleted from the Sign Bank.  I will modify the gloss in the SignStream file to be: (2h)alt.ASK_2+++:i

**Comment by kwasiopoku** [comment]
Fixed
