### ISSUE TITLE
Missing images and videos on the DAI

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/ASL-DAI#189]
<img width="1193" alt="Screen Shot 2019-09-30 at 8 03 07 PM" src="https://user-images.githubusercontent.com/13629122/65925128-8ae37f80-e3bd-11e9-82a7-fce8b31da7af.png">

<img width="789" alt="Screen Shot 2019-09-30 at 8 03 22 PM" src="https://user-images.githubusercontent.com/13629122/65925131-90d96080-e3bd-11e9-9183-44590a5b8e53.png">

**Comment by cneidle** [comment]
another one

<img width="1170" alt="Screen Shot 2019-09-30 at 8 18 41 PM" src="https://user-images.githubusercontent.com/13629122/65925625-9df74f00-e3bf-11e9-9977-734c963c2cb2.png">


<img width="790" alt="Screen Shot 2019-09-30 at 8 18 48 PM" src="https://user-images.githubusercontent.com/13629122/65925624-9df74f00-e3bf-11e9-8f08-30ebece4aeeb.png">

**Comment by cneidle** [comment]
<img width="1192" alt="Screen Shot 2019-09-30 at 8 20 30 PM" src="https://user-images.githubusercontent.com/13629122/65925715-f0d10680-e3bf-11e9-950d-db57f1cbb4cd.png">

**Comment by cneidle** [comment]
the higher level headings in these cases shows a ?

<img width="1113" alt="Screen Shot 2019-09-30 at 8 23 00 PM" src="https://user-images.githubusercontent.com/13629122/65925781-355ca200-e3c0-11e9-9ef2-1cefe98b5ceb.png">

**Comment by kwasiopoku** [comment]
This is fixed and tested in both dev and dai

**Comment by cneidle** [comment]
This is not fixed currently on the DAI

I thought that display of the higher-level item HAD been disabled, but that is not the current state.

<img width="1190" alt="Screen Shot 2020-01-26 at 11 21 21 AM" src="https://user-images.githubusercontent.com/13629122/73138201-0d0f4800-402e-11ea-98fb-371eb2769649.png">

**Comment by kwasiopoku** [comment]
I have updated 241 main glosses that were impacted by this

mysql> update signbank_gloss g set id_DefaultVariant = (select min(id_SignBankVariant) from signbank_variant v where v.id_SignBankGloss = g.id_SignBankGloss) where id_DefaultVariant is NULL and id_SignBankGloss in (select id_SignBankGloss from signbank_variant);
Query OK, 241 rows affected (0.99 sec)
Rows matched: 241  Changed: 241  Warnings: 0
