### ISSUE TITLE
Pagination seems to have stopped working

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/ASL-DAI#218]
for display of search results

**Comment by kwasiopoku** [comment]
Done

**Comment by cneidle** [comment]
Pagination still not working from the main sign search page.  Not a high priority, but it would be good if that could be implemented at some point.  It takes forever to load, and scroll through, all the results if you do a search for all signs, for example...  Thanks.
