### ISSUE TITLE
Buttons - odd behavior if you choose to open the linked item in a separate tab or window

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/ASL-DAI#221]
Hi Augustine,

If you just click on the Help button from the Statistics page (see below), it opens up the document it is supposed to.  But if you Control-click and choose to open the linked file in a separate tab or window (from the contextual menu), it opens instead the old Help page: http://dai.cs.rutgers.edu/dai/s/help

This is the same from this page with the other buttons that were recently modified.  Choosing to open the linked item in a separate tab or window brings back what the link had before, e.g., a broken link in many cases.

Not sure why the old URLs are still hidden there and retrieved by trying to open in a separate tab or window.

But the same thing seems to happen systematically with buttons on the other page as well that were recently modified... 

<img width="1140" alt="Screen Shot 2020-05-23 at 11 51 03 AM" src="https://user-images.githubusercontent.com/13629122/82735015-896c1c00-9cec-11ea-9694-6d3683d8ea7d.png">

**Comment by cneidle** [comment]
Many of the buttons work better now.   But the Acknowledgments and Credits button still has the above-described behavior, from all pages that have that button.  Just FYI.

**Comment by kwasiopoku** [comment]
Fixed

**Comment by cneidle** [comment]
Some of these are still broken - same button broken both from the Sign Search and Utterance Search pages and also the Statistics page and also from the other pages resulting from a sign or utterance search, if you attempt to open them in a new window:

<img width="977" alt="Screen Shot 2020-06-21 at 11 44 26 AM" src="https://user-images.githubusercontent.com/13629122/85228942-add31b00-b3b4-11ea-8631-8712a809e007.png">

===============


<img width="978" alt="Screen Shot 2020-06-21 at 11 51 41 AM" src="https://user-images.githubusercontent.com/13629122/85229065-99435280-b3b5-11ea-9d2d-f7d2ed726a33.png">

===============

<img width="1019" alt="Screen Shot 2020-06-21 at 11 52 40 AM" src="https://user-images.githubusercontent.com/13629122/85229086-c263e300-b3b5-11ea-8f96-6cadd5878e78.png">

**Comment by cneidle** [comment]
Also - we should have a TERMS OF USE button on the Sign Bank page.

thanks.

**Comment by cneidle** [comment]
I thought this had been fixed but this is still broken, from https://dai.cs.rutgers.edu/dai/s/Acknowledgments%20&%20Credits:


<img width="354" alt="Screen Shot 2021-03-27 at 3 56 54 PM" src="https://user-images.githubusercontent.com/13629122/112733274-446cd380-8f15-11eb-896e-75a0ad730023.png">

**Comment by cneidle** [comment]
This problem still has not been fixed.
