### ISSUE TITLE
MANY vs. HOW-MANY/MANY

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/ASL-DAI#223]
Some time ago, we made some changes to the Sign Bank, to separate out what had previously been listed as  MANY/HOW-MANY into two distinct signs:  MANY and HOW-MANY (and similarly for the 1-handed versions of these:  There should now be (1h)MANY as distinct from (1h)HOW-MANY).

That seems to have gotten messed up over time, however.

This much is correct:

<img width="931" alt="Screen Shot 2020-05-28 at 1 42 46 PM" src="https://user-images.githubusercontent.com/13629122/83174943-27932400-a0e9-11ea-9b0d-594b192136c1.png">

<img width="792" alt="Screen Shot 2020-06-13 at 12 04 50 PM" src="https://user-images.githubusercontent.com/13629122/84573399-3545dc00-ad6e-11ea-891c-89b9c0ac4fff.png">

---------

However, we also have this - and note that the ASLLVD Sign Bank entry is correctly glossed as MANY, but not grouped with the other examples of MANY.  (I will need to fix the two occurrences from the continuous signing data and then reupload those files.)

<img width="894" alt="Screen Shot 2020-05-28 at 1 43 36 PM" src="https://user-images.githubusercontent.com/13629122/83175043-4db8c400-a0e9-11ea-8bfc-509f2c2b6c32.png">

Can you fix the problem with this ASLLVD Sign Bank entry?  It should be grouped with the other MANY signs.

I will also need to fix this one:

<img width="784" alt="Screen Shot 2020-05-28 at 1 46 30 PM" src="https://user-images.githubusercontent.com/13629122/83175306-b30cb500-a0e9-11ea-96a1-e4be3ca0b42e.png">

THANKS!

**Comment by kwasiopoku** [comment]
Fixed

**Comment by cneidle** [comment]
Not quite fixed.  Things have moved as they needed to, but the ASLLVD data is still showing up for HOW-MANY/MANY

<img width="966" alt="Screen Shot 2020-06-20 at 6 34 46 PM" src="https://user-images.githubusercontent.com/13629122/85212847-dc091a00-b324-11ea-8d15-1c87707c09c7.png">

**Comment by kwasiopoku** [comment]
Fixed
