### ISSUE TITLE
several corrections needed to ASLLVD data

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/ASL-DAI#225]
For some reason, one entry for "SOUP" is glossed as "SOUP+poi". that is a mistake.  the "+poi" needs to be deleted.  (Our fault.  It is like this in the Ashwin data... ).  Thanks.

<img width="1048" alt="Screen Shot 2020-06-04 at 3 20 03 PM" src="https://user-images.githubusercontent.com/13629122/83801417-190fb400-a677-11ea-93ad-615ee64e2b4b.png">

**Comment by cneidle** [comment]
Several corrections will be needed to the ASLLVD data - THANK YOU !!!!!

<1> "(A)ns-ASIA"   should be moved to become a variant under main entry: "ns-ASIA"

DONE - THANK YOU.

<2> "BEAT_2"   should moved to become a variant under main entry: "BEAT" 

DONE - THANK YOU.

<3> Right now we have two main entries, "BUILD" and "BUILDING".  We should have only "BUILD".
The entry variant "(U-L)BUILDING" should be moved in under main entry 'BUILD".
And the signs currently listed under entry variant = "BUILD_2" should be relabelled as "(U-L)BUILD".

So we should end up with

BUILD
- BUILD
- (U-L)BUILD [incorporating what is currently listed as BUILD_2 (the glosses will need to be changed) and (U-L)BUILDING (the glosses will also need to be changed)].

<img width="133" alt="Screen Shot 2020-06-07 at 12 48 53 PM" src="https://user-images.githubusercontent.com/13629122/83974811-089d4a80-a8be-11ea-95cc-c29d8353f4b3.png">

So, all 7 of the signs below should be reglossed as "(U-L)BUILD", an entry/variant under "BUILD".

<img width="788" alt="Screen Shot 2020-06-07 at 12 49 23 PM" src="https://user-images.githubusercontent.com/13629122/83974819-1521a300-a8be-11ea-817e-6f6cd49024f6.png">

<img width="789" alt="Screen Shot 2020-06-07 at 12 49 12 PM" src="https://user-images.githubusercontent.com/13629122/83974817-0fc45880-a8be-11ea-89e8-ed48f14e34b7.png">

DONE - THANK YOU

<4> "BEST" should be moved in as an entry/variant under "BETTER".  So, no glosses will need to be changed, but we should end up with

BETTER
- BETTER
- BEST

DONE - THANK YOU

Sorry for the inconvenience !!!!

THANK YOU VERY MUCH!






totally done - THANK YOU

**Comment by cneidle** [comment]
One last (I hope!) request:

we should change the few examples of EVENING to NIGHT.  These three signs should be reglossed as NIGHT and moved in with all the other examples of NIGHT:

<img width="787" alt="Screen Shot 2020-06-10 at 9 44 49 AM" src="https://user-images.githubusercontent.com/13629122/84275502-25749080-aaff-11ea-970a-7a3921adb797.png">

And EVENING should be removed permanently from the inventory of possible main entries (rather than laying dormant).

THANK YOU !!!


DONE - THANK YOU

**Comment by cneidle** [comment]
ONE MORE small one:

Could you please move ns-GREECE_2 to be an entry variant under ns-GREECE?

i.e.,

ns-GREECE
- ns-GREECE
- ns-GREECE_2

Thank you !!



<img width="183" alt="Screen Shot 2020-06-10 at 12 40 37 PM" src="https://user-images.githubusercontent.com/13629122/84294773-a63f8680-ab17-11ea-80f7-be1336dd634c.png">

**JUNE 11 - UPDATE - AFTER CHANGES WERE MADE**

This one is not right.   "ns-GREECE_2" should be a lexical variant under ns-GREECE.

Right now it is not separated out:

<img width="789" alt="Screen Shot 2020-06-11 at 1 07 59 PM" src="https://user-images.githubusercontent.com/13629122/84418103-a6598800-abe4-11ea-9be1-5a37e7f4b569.png">

**Comment by cneidle** [comment]
ONE MORE - after our conversation last night:  

Could you please put HEAVEN_2 and HEAVEN_3 and variants under HEAVEN.

So we would have

HEAVEN
- HEAVEN
- HEAVEN_2
- HEAVEN_3

thank you !!!!

**Comment by kwasiopoku** [comment]
Done.

**Comment by cneidle** [comment]
THANK YOU, AUGUSTINE !!   Note there is still an issue with the ns-GREECE; see above.

And you probably didn't notice that I added one last item:  HEAVEN.  

THANKS SO MUCH !

**Comment by cneidle** [comment]
Another one - sorry !

Could you please change the gloss for the 3 occurrences of INSTEAD to REPLACE, and move them in with the other occurrences of REPLACE?   

<img width="113" alt="Screen Shot 2020-06-12 at 11 01 57 AM" src="https://user-images.githubusercontent.com/13629122/84516824-576f2980-ac9c-11ea-8c84-35236fb95c2c.png">

<img width="538" alt="Screen Shot 2020-06-12 at 11 02 04 AM" src="https://user-images.githubusercontent.com/13629122/84516822-56d69300-ac9c-11ea-95e7-98a98af6e122.png">

<img width="1107" alt="Screen Shot 2020-06-12 at 11 04 10 AM" src="https://user-images.githubusercontent.com/13629122/84516902-7bcb0600-ac9c-11ea-974c-b2dfc2a8659f.png">

**Comment by kwasiopoku** [comment]
Fixed

**Comment by cneidle** [comment]
ONE MORE (sorry!):

Could you please change TYPEWRITER_2 to TYPE (changing the gloss).

<img width="776" alt="Screen Shot 2020-06-13 at 11 55 31 AM" src="https://user-images.githubusercontent.com/13629122/84573179-d9c71e80-ad6c-11ea-8336-95985f67457f.png">

Also, please move TYPEWRITER so that it is an entry/variant under TYPE.

<img width="207" alt="Screen Shot 2020-06-13 at 11 50 35 AM" src="https://user-images.githubusercontent.com/13629122/84573095-74732d80-ad6c-11ea-9fcc-dbb40dca0087.png">

RESULT:

TYPE
- TYPE [now to include what was previously TYPEWRITER_2]
- TYPEWRITER

Thank you !!!

**Comment by cneidle** [comment]
ANOTHER ONE:  Could you please make KNEELING an entry/variant under KNEEL?

<img width="122" alt="Screen Shot 2020-06-13 at 12 51 01 PM" src="https://user-images.githubusercontent.com/13629122/84574479-abe5d800-ad74-11ea-9794-d90031071d75.png">

We we would end up with:

KNEEL
- KNEEL
- KNEELING

and KNEELING can be deleted as a possible main entry.

Thank you !!

**Comment by cneidle** [comment]
Corrections still needed above for:

INSTEAD
TYPE
KNEEL

Thank you !


LOOKS GREAT - thanks !!

**Comment by kwasiopoku** [comment]
Fixed

**Comment by cneidle** [comment]
ONE MORE Request (so sorry!).

Could you please change the glosses and entry from ns-PITTSBURGH to ns-PITTSBURGH/MAINE?

SO when you're done, we will have

ns-PITTSBURGH/MAINE
- ns-PITTSBURGH/MAINE (2)

<img width="995" alt="Screen Shot 2020-06-20 at 6 33 03 PM" src="https://user-images.githubusercontent.com/13629122/85212884-3609df80-b325-11ea-9a3e-34d203cb20f7.png">

THANK YOU !

**Comment by kwasiopoku** [comment]
Fixed

**Comment by cneidle** [comment]
The original sign fs-MAINE also needs to be changed to ns-PITTSBURGH/MAINE.   Thanks !!!

<img width="668" alt="Screen Shot 2020-07-28 at 11 23 13 AM" src="https://user-images.githubusercontent.com/13629122/88686644-4a2fc200-d0c5-11ea-966e-119a30fcbcec.png">

**Comment by cneidle** [comment]
Everything above is resolved, except for the last item.  Thanks!

**Comment by kwasiopoku** [comment]
This has been resolved on dev1
