### ISSUE TITLE
Wish List

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/ASL-DAI#240]
Hi,  I just want to record the things we discussed the other day, so that they don't get forgotten :-)

0) You were going to investigate how to classify signs that include a + sign in the gloss (for reasons other than combining the parts of compounds) without the "+" appearing in the gloss that appears in the index on the left.

   Here the + will need to be removed:

<img width="296" alt="Screen Shot 2020-09-11 at 1 30 27 PM" src="https://user-images.githubusercontent.com/13629122/92956399-c8a5b080-f434-11ea-9305-f53489ddcb55.png">

the above looks good :-)

<img width="167" alt="Screen Shot 2020-09-11 at 1 48 31 PM" src="https://user-images.githubusercontent.com/13629122/92956822-87fa6700-f435-11ea-9211-4ced2ca29d1a.png">

the above looks good :-)

<img width="291" alt="Screen Shot 2020-09-11 at 1 54 48 PM" src="https://user-images.githubusercontent.com/13629122/92957376-6cdc2700-f436-11ea-967d-cbaf0280c3f5.png">

the above looks good :-)

<img width="205" alt="Screen Shot 2020-09-11 at 1 56 21 PM" src="https://user-images.githubusercontent.com/13629122/92957500-9e54f280-f436-11ea-8084-3f11c97de144.png">

<img width="252" alt="Screen Shot 2020-09-11 at 2 04 14 PM" src="https://user-images.githubusercontent.com/13629122/92958151-b6794180-f437-11ea-8a9c-af6297de2480.png">

<img width="201" alt="Screen Shot 2020-09-11 at 2 04 46 PM" src="https://user-images.githubusercontent.com/13629122/92958202-cabd3e80-f437-11ea-92f6-d688156605db.png">

<img width="191" alt="Screen Shot 2020-09-11 at 2 08 52 PM" src="https://user-images.githubusercontent.com/13629122/92958513-5c2cb080-f438-11ea-81ef-df737af82754.png">

the above looks good :-)

<img width="234" alt="Screen Shot 2020-09-11 at 2 11 42 PM" src="https://user-images.githubusercontent.com/13629122/92958723-bf1e4780-f438-11ea-9f53-467ddb7b4275.png">

the above looks good :-)

==

The +'s here are quite strange!

<img width="298" alt="Screen Shot 2020-09-11 at 2 01 20 PM" src="https://user-images.githubusercontent.com/13629122/92957896-51bde700-f437-11ea-8efd-eda7099131a7.png">

==

1) It would be great to be able to keep track of a sign example that has been chosen to be the canonical one, even after a file is re-uploaded.  You mentioned that there are sufficient identifiers to make this possible...

2) It would be very helpful to have dev1 accessible without requiring a VPN.  You mentioned you were going to ask about doing this.  This would make it possible for our students to connect, without having authorization for the VPN.

3) It would be very helpful to have accounts that are intermediary between general public accounts (for downloading data) and full admin accounts.  Specifically, students should have access to viewing private data, but *not* to classifying signs or making other changes to the database -- other than selecting the canonical form (once it becomes possible to retain those selections, as in (1) above).   This will make it possible for students to view and verify data (notifying me of any problems), without risking that they may make inappropriate changes to the site.

Thank you so much!  and also for making the corrections remaining in #237 and #239.

**Comment by cneidle** [comment]
Also, we talked about renaming the buttons for the Sign Bank isolated signs to:  "Play whole clip" and "Play sign video".
For the ASLLVD and the RIT data, the only option will be "Play whole clip."   For the DawnSignPress isolated signs, both options will be available.  For the signs from the continuous signing (ours, or DSP), the only option will be "play sign video" (in addition to "play utterance").

We also talked about relabeling the menu options to be:

Files: ASLLRP sentences
Files: DSP isolated signs
Files: DSP sentences
Files: RIT isolated signs

We might also change the labels on the Sign Bank display page accordingly:

ASLLVD isolated signs
ASLLRP signs from sentences
DawnSignPress isolated signs
DawnSignPress signs from sentences
RIT isolated signs

thanks so much !!

**Comment by cneidle** [comment]
When we make the DSP data publicly available, we will have to update the terms of use, as the use of their data is more restrictive.

Eventually, we should also update the statistics page to display the counts from these other data sets, but that is really for the future :-)

We have also discussed possible ways to share the ASLLVD data...  also for future consideration.

**Comment by kwasiopoku** [comment]
Signbank database has been update to correct the classification errors.  
Collection link labels have also been updated
SIgnbank collection display headers have also been updated accordingly

**Comment by cneidle** [comment]
THANK YOU !

One of the cases with a + was not corrected:

<img width="239" alt="Screen Shot 2020-09-13 at 8 51 44 AM" src="https://user-images.githubusercontent.com/13629122/93018581-c7909280-f59e-11ea-883b-cd9d2c05650d.png">

Also I noticed this entry, which is way out of alphabetical order:

<img width="169" alt="Screen Shot 2020-09-13 at 8 52 14 AM" src="https://user-images.githubusercontent.com/13629122/93018585-d37c5480-f59e-11ea-813b-886207935d3f.png">

**Comment by cneidle** [comment]
There are starting to be a LOT of signs...  I wonder about the possibility of paging when the number of results is large.  Or else perhaps links at the top of every page to jump to:

ASLLVP isolated signs
ASLLRP signs from sentences
DawnSignPress isolated signs
DawnSIgnPress signs from sentences
RIT isolated signs

**Comment by kwasiopoku** [comment]
@cneidle these items have been fixed.

**Comment by kwasiopoku** [comment]
Is okay if I move the remaining items relating to pagination and updating data policy to a different ticket and then close this one once you verify that the updates look good?

**Comment by cneidle** [comment]
of course 

thanks !!!

will check the rest by the end of the day :-)

cheers,
 Carol

**Comment by cneidle** [comment]
Why do these numbers not match?

<img width="167" alt="Screen Shot 2020-10-09 at 12 53 39 PM" src="https://user-images.githubusercontent.com/13629122/95610581-8b7e0f80-0a2e-11eb-9290-fa558bb22f29.png">

<img width="113" alt="Screen Shot 2020-10-09 at 12 53 34 PM" src="https://user-images.githubusercontent.com/13629122/95610587-8c16a600-0a2e-11eb-8f75-2c38cdf6e096.png">

**Comment by cneidle** [comment]
same as above

<img width="192" alt="Screen Shot 2020-10-09 at 12 55 50 PM" src="https://user-images.githubusercontent.com/13629122/95610765-cc762400-0a2e-11eb-8c87-b2931f61f538.png">

<img width="171" alt="Screen Shot 2020-10-09 at 12 55 44 PM" src="https://user-images.githubusercontent.com/13629122/95610767-cd0eba80-0a2e-11eb-9a3a-0490b0bd1864.png">

**Comment by cneidle** [comment]
same

<img width="217" alt="Screen Shot 2020-10-09 at 12 56 55 PM" src="https://user-images.githubusercontent.com/13629122/95610848-f4fe1e00-0a2e-11eb-938b-0f9114f9e7cc.png">

<img width="176" alt="Screen Shot 2020-10-09 at 12 56 49 PM" src="https://user-images.githubusercontent.com/13629122/95610849-f596b480-0a2e-11eb-96e2-4677e7336b03.png">

**Comment by cneidle** [comment]
The extra + still appears in the occurrence window

<img width="784" alt="Screen Shot 2020-10-09 at 4 52 54 PM" src="https://user-images.githubusercontent.com/13629122/95630517-f986fe80-0a4f-11eb-9a4b-34f968c626ac.png">
:

**Comment by cneidle** [comment]
The general problem with sorting has not been resolved.  As we discussed, items that are to be disregarded for purposes of sorting should only be disregarded when they occur at the beginning of a sign, not at the beginning of the second part of a compound.

**Comment by kwasiopoku** [comment]
I have updated *+(1h)MOST (LONG++(1h)MOST) .  I found one move occurrence with a preceding "+".  I have corrected *+(1h)MOST (OLD++(1h)MOST) as well

LOOKS GOOD - THANK YOU !  - CN (10/12)

**Comment by cneidle** [comment]
This problem is back again!

<img width="310" alt="Screen Shot 2022-01-02 at 5 19 56 PM" src="https://user-images.githubusercontent.com/13629122/147890866-a51fb4c6-de5c-4179-a58a-7f6f60887f1c.png">

everything else above seems to be ok, except for the general sorting problems.

**Comment by cneidle** [comment]
DIFFERENT+-arc is still showing up wtih the +.
"-arc" has the same status as. "-1p" or "-2p" etc.  
Thanks.
