### ISSUE TITLE
Reminder of pending issues: 1-handed signs on non-dom hand and "WHAT"

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/ASL-DAI#263]
1"focus" is still showing up; I thought that had been fixed, no?

And "WHAT" should be alphabetized with W (i.e., ignoring the initial ")

THANKS

**Comment by kwasiopoku** [comment]
This has been resolved.  Thanks

**Comment by cneidle** [comment]
This is still showing up...

<img width="76" alt="Screen Shot 2020-11-26 at 4 20 56 PM" src="https://user-images.githubusercontent.com/13629122/100392077-686de600-3003-11eb-8232-1bbec2253f78.png">

**Comment by kwasiopoku** [comment]
The occurrences were removed but the entry variants and primary entries were still in the db.  Those have also been removed now

**Comment by cneidle** [comment]
thanks
