### ISSUE TITLE
VIews still not corrected in the "secrets" reincarnation

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/ASL-DAI#281]
The thumbnails are still randomly taken from front, side, and face close-up views, whereas they should all be front views.

<img width="430" alt="Screen Shot 2021-02-03 at 5 57 04 PM" src="https://user-images.githubusercontent.com/13629122/106820390-3f904f80-6649-11eb-8be9-017db895059a.png">

**Comment by cneidle** [comment]
this still needs to be taken care of.

**Comment by kwasiopoku** [comment]
This issue has been resolved.

**Comment by cneidle** [comment]
not resolved

<img width="455" alt="Screen Shot 2022-01-20 at 10 31 41 AM" src="https://user-images.githubusercontent.com/13629122/150369825-9fc7ffea-17d5-4c67-b363-352a9dd45101.png">

**Comment by cneidle** [comment]
definitely still not fixed!  we should be displaying the front views consistently , not face close-ups

<img width="1134" alt="Screen Shot 2022-01-22 at 3 57 55 PM" src="https://user-images.githubusercontent.com/13629122/150655301-6ccf2ac8-a919-4cfc-b41e-6fcd821da3c0.png">

<img width="1464" alt="Screen Shot 2022-01-22 at 3 57 05 PM" src="https://user-images.githubusercontent.com/13629122/150655303-908d7e80-2ab6-4b3d-9259-be8fff07edc6.png">

**Comment by cneidle** [comment]
still not fixed.

**Comment by cneidle** [comment]
still not fixed

**Comment by cneidle** [comment]
there are identical start images displayed, rather than 1 start and 1 end

<img width="954" alt="Screen Shot 2022-11-25 at 3 34 30 PM" src="https://user-images.githubusercontent.com/13629122/204053266-f6bd515c-16c1-4a27-9119-48d13c436a79.png">
