### ISSUE TITLE
DAI:  Wrong image showing up in the right-hand pane

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/ASL-DAI#299]
<img width="1313" alt="Screen Shot 2022-02-04 at 2 51 32 PM" src="https://user-images.githubusercontent.com/13629122/152594246-894908d6-798d-497d-9022-860cdd46344b.png">

The upper image is wrong.

The one in the separate window is correct.

Thanks.

**Comment by cneidle** [comment]
Same error in dev1

**Comment by kwasiopoku** [comment]
This has been resolved on dev1 & dai

**Comment by cneidle** [comment]
Still a problem -

<img width="1189" alt="Screen Shot 2022-02-07 at 10 23 56 AM" src="https://user-images.githubusercontent.com/13629122/152817644-075b48a2-abcf-4719-b519-40a61a2d0bd2.png">

**Comment by cneidle** [comment]
fixed - thank you
