### ISSUE TITLE
Need to display the canonical form for cases like GOOD/THANK-YOU

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/ASL-DAI#425]
<img width="938" alt="Screen Shot 2023-03-14 at 10 35 57 PM" src="https://user-images.githubusercontent.com/13629122/225190711-500a1617-28a8-45a9-82c2-924060f4b8e4.png">

**Comment by cneidle** [comment]
You can test this with:   videos/other/zx-WLASL-COME-HERE_2-11867.mp4

**Comment by kwasiopoku** [comment]
This has been resolved on dev1.cs

**Comment by cneidle** [comment]
NO - this is still not fixed. (1h)GOOD/THANK-YOU needs to be on top...

<img width="887" alt="Screen Shot 2023-03-30 at 4 13 56 PM" src="https://user-images.githubusercontent.com/13629122/228953767-5d1d8cf9-9d92-47ea-8c07-e1041eb4a096.png">

**Comment by kwasiopoku** [comment]
The sort order has been fixed on dev1.cs

**Comment by cneidle** [comment]
This seems to have been fixed.
