### ISSUE TITLE
Weird issue in capitalization of B

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/ASL-DAI#429]
I believe I corrected the file so that crvd-b was corrected to crvd-B.  But the main entry listing did not get corrected.

<img width="1191" alt="Screen Shot 2023-03-22 at 9 31 38 PM" src="https://user-images.githubusercontent.com/13629122/227075938-6d5f8a7f-f557-4c95-826e-c235eb3349df.png">

**Comment by cneidle** [comment]
I only found one more like this:

<img width="1287" alt="Screen Shot 2023-03-22 at 10 24 30 PM" src="https://user-images.githubusercontent.com/13629122/227084294-7412f645-e2f5-42cc-b941-27257c06136c.png">

**Comment by kwasiopoku** [comment]
This has been resolved on dev1

**Comment by cneidle** [comment]
Still not resolved on DAI


<img width="239" alt="Screen Shot 2023-11-19 at 1 41 26 PM" src="https://github.com/DCS-LCSR/ASL-DAI/assets/13629122/6edc64bc-5cee-4061-9367-2f58ac2757ca">

**Comment by kwasiopoku** [comment]
This has been resolved
