### ISSUE TITLE
a couple of small inconsistencies in the Sign Bank annotations

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/ASL-DAI#507]
I found a couple of signs glossed as finger spelled which should be loan signs, i.e., fs-APT and fs-ABC should be #APT and #ABC.

<img width="921" height="256" alt="Image" src="https://github.com/user-attachments/assets/91430d37-236b-4f8a-ba53-f1c4f390669a" />

<img width="684" height="175" alt="Image" src="https://github.com/user-attachments/assets/a5bad4aa-0d0c-4aac-95f7-39a4b2511ae3" />

**Comment by kwasiopoku** [comment]
This has been updated on dev1 and dai

**Comment by cneidle** [comment]
Actually, the fix is not complete.  This needs to be changed in the listings:

<img width="159" height="87" alt="Image" src="https://github.com/user-attachments/assets/800126b6-6a96-44bf-ab9c-9f445fc700e6" />

<img width="105" height="76" alt="Image" src="https://github.com/user-attachments/assets/c118f9c7-0dc4-4c62-a13d-bbf9f0f2523f" />

and the sign variant labels need to be changed as well, and merged with the other occurrences of the #signs:

<img width="931" height="363" alt="Image" src="https://github.com/user-attachments/assets/109890a6-f763-419e-b37c-d43d837a4603" />

<img width="1062" height="590" alt="Image" src="https://github.com/user-attachments/assets/655ae203-7d9e-407e-989c-2d6ff62b3d2b" />

Same for the other one...

Thanks in advance for taking care of this!

**Comment by kwasiopoku** [comment]
The primary entry and the entry variant have also been resolved.  Thanks Carol

**Comment by cneidle** [comment]
Progress!  THANKS!  **BUT** why are these still listed separately ??

<img width="246" height="77" alt="Image" src="https://github.com/user-attachments/assets/437489aa-6c46-44ab-9968-c67671c84625" />


<img width="105" height="52" alt="Image" src="https://github.com/user-attachments/assets/c566de9b-fe1f-4ab0-82b2-2bcd313dda78" />

**Comment by kwasiopoku** [comment]
This is now fixed

**Comment by cneidle** [comment]
**This has still NOT been fixed.**

<img width="105" height="59" alt="Image" src="https://github.com/user-attachments/assets/c83eb316-0118-4c93-9826-ee48bbbee1a7" />



<img width="136" height="70" alt="Image" src="https://github.com/user-attachments/assets/6c1cc520-1ce2-4aa4-a540-e7c712be2f4f" />
