### ISSUE TITLE
Duplicated counts in DAI search result

### ISSUE THREAD

**Issue by kwasiopoku** [DCS-LCSR/ASL-DAI#70]
For example CAR(98).  Looks like the result includes duplicates for both hands

**Comment by kwasiopoku** [comment]
Fixed

**Comment by cneidle** [comment]
Hi Augustine.  On the Dai public server, we're still getting (or again getting) double counts, cf.
below - there are 2 of each of these, 4 in all.  Thanks.

<img width="637" alt="Screen Shot 2019-06-10 at 3 54 05 PM" src="https://user-images.githubusercontent.com/13629122/59222729-2d21f200-8b98-11e9-9590-438aa6e67ad3.png">

**Comment by cneidle** [comment]
This is still a problem!

<img width="1256" alt="Screen Shot 2022-08-17 at 8 16 47 AM" src="https://user-images.githubusercontent.com/13629122/185116458-09454c41-a7ef-4fad-9dd3-79a88f24e568.png">

<img width="464" alt="Screen Shot 2022-08-17 at 8 16 22 AM" src="https://user-images.githubusercontent.com/13629122/185116488-c3fad6fa-e7f2-48c1-978e-90bb9704efab.png">

**Comment by cneidle** [comment]
This is still a problem.

**Comment by cneidle** [comment]
this is still a problem

**Comment by cneidle** [comment]
Still a problem.

**Comment by kwasiopoku** [comment]
This has been resolved on dev1.cs and dai.cs
