### ISSUE TITLE
incorrect image in the handshape selection palette

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/ASL-DAI#87]
See email forwarded from Thomas Stone:

I was looking through the Handshape selection feature of your DAI 2 version 1.0 form.

http://dai.cs.rutgers.edu/dai/s/dai

I saw selecting the "Start HS" button shows a pop-up page that shows handshape pictures.

http://dai.cs.rutgers.edu/dai/s/handshape?hand=nd_start

I noticed the picture for one handshape, the letter M, was mis-linked to the same picture as the previous handshape in the list, the loose-E. Having selected the letter M, the same loose-E picture was returned to the "Start HS" box. However, selecting the "SUBMIT" button redirected me to the results page, which included the correct letter M picture.

____

The M picture should be:

<img width="616" alt="screen shot 2018-06-08 at 11 54 21 am" src="https://user-images.githubusercontent.com/13629122/41168035-c12b2a4a-6b12-11e8-8216-eff9f0d3cc1d.png">

as on http://www.bu.edu/asllrp/cslgr/pages/ncslgr-handshapes.html

**Comment by kwasiopoku** [comment]
Fixed

**Comment by cneidle** [comment]
Still happening

<img width="72" alt="Screen Shot 2020-01-08 at 9 55 14 PM" src="https://user-images.githubusercontent.com/13629122/72034003-d7aee000-3261-11ea-92a3-a6567404f7fe.png">
<img width="1194" alt="Screen Shot 2020-01-08 at 9 54 38 PM" src="https://user-images.githubusercontent.com/13629122/72034004-d7aee000-3261-11ea-9331-6d8fb420f02c.png">

**Comment by kwasiopoku** [comment]
This was resolved and reviewed with Carol

**Comment by cneidle** [comment]
Sorry but this is still not fixed.

I go the handshape palette and click on M but what appears in the search box is a different handshape.

<img width="88" alt="Screen Shot 2020-01-26 at 11 23 36 AM" src="https://user-images.githubusercontent.com/13629122/73138227-624b5980-402e-11ea-8db6-f8c1cf40f42d.png">

<img width="335" alt="Screen Shot 2020-01-26 at 11 23 42 AM" src="https://user-images.githubusercontent.com/13629122/73138229-67100d80-402e-11ea-9bf0-a2fbca2c94e7.png">

**Comment by kwasiopoku** [comment]
This is resolved now.
