### ISSUE TITLE
Missing handshapes and other DAI display issues - July 2, 2018

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/ASL-DAI#91]
Please see attached.

[DAI-problems-handshapes-and-more.pdf](https://github.com/DCS-LCSR/ASL-DAI/files/2156305/DAI-problems-handshapes-and-more.pdf)

**Comment by kwasiopoku** [comment]
Fixed

**Comment by cneidle** [comment]
Some/many of the problems that were reported are indeed now fixed.  

HOWEVER:

Still a problem with #IF

<img width="753" alt="screen shot 2018-08-01 at 7 01 36 am" src="https://user-images.githubusercontent.com/13629122/43518079-d62c3b44-9558-11e8-9c0b-1c6b321f801f.png">

Also with #REF, #FF, #FF_2, #OFF, (f/9)WHISTLE, #FIX

Also: ALWAYS

<img width="670" alt="screen shot 2018-08-01 at 7 05 49 am" src="https://user-images.githubusercontent.com/13629122/43518223-62a0207c-9559-11e8-9b4c-3b20b725b1a6.png">

#CLUB 

<img width="726" alt="screen shot 2018-08-01 at 7 07 36 am" src="https://user-images.githubusercontent.com/13629122/43518298-a0c5d72a-9559-11e8-8b20-73f49d4baf5b.png">

#BUS 

<img width="671" alt="screen shot 2018-08-01 at 7 08 22 am" src="https://user-images.githubusercontent.com/13629122/43518327-b9da3fc6-9559-11e8-8198-0ebb595764bb.png">

 ARM

<img width="761" alt="screen shot 2018-08-01 at 7 11 04 am" src="https://user-images.githubusercontent.com/13629122/43518446-1b0367d2-955a-11e8-9151-355578bab64d.png">


Weirdness with ALL-NIGHT-AFTER-MIDNIGHT also remains.

**Comment by cneidle** [comment]
Still problematic:

ALWAYS (top line)

![Screen Shot 2019-07-08 at 10 53 53 AM](https://user-images.githubusercontent.com/13629122/60820096-bfed8680-a16e-11e9-8cca-8fcf06b5f566.png)

ARM (lines 2 and 4)

![Screen Shot 2019-07-08 at 10 55 19 AM](https://user-images.githubusercontent.com/13629122/60820185-eca19e00-a16e-11e9-861a-9ecb34258c72.png)

Also (3)INJECT:

![Screen Shot 2019-07-08 at 11 00 33 AM](https://user-images.githubusercontent.com/13629122/60820554-a862cd80-a16f-11e9-87b5-92a3291cfd5f.png)


And INJECT:

![Screen Shot 2019-07-08 at 11 06 24 AM](https://user-images.githubusercontent.com/13629122/60820911-756d0980-a170-11e9-9ca8-453c623ee4db.png)


For #CLUB, the example from the continuous signing has 4 handshapes (I just verified that it has been correctly annotated:  C - L - U - B.   But the final handshape is showing up as "L" rather than "B".

![Screen Shot 2019-07-08 at 11 03 56 AM](https://user-images.githubusercontent.com/13629122/60820798-35a62200-a170-11e9-9e36-7163f3832680.png)

Same problem with #BUS, showing up with final handshape "U" in the continuous signing example rather than "S".

![Screen Shot 2019-07-08 at 11 05 16 AM](https://user-images.githubusercontent.com/13629122/60820855-59696800-a170-11e9-91e4-67cf92f86a87.png)


#NO has one example missing handshapes:

![Screen Shot 2019-07-08 at 11 08 19 AM](https://user-images.githubusercontent.com/13629122/60821046-c0871c80-a170-11e9-943b-463caf83d118.png)

I'm going to enter these and continue... 

thanks!

**Comment by cneidle** [comment]
The only other problem I see from #91 is this -- which really belongs now with ticket #126:

![Screen Shot 2019-07-08 at 11 14 29 AM](https://user-images.githubusercontent.com/13629122/60821545-bdd8f700-a171-11e9-8235-d79129d5a2b8.png)

**Comment by cneidle** [comment]
Note that the handshape issues that affect the continuous signing data for loan signs.
E.g. #BUS    Should have end handshape "S" as it does for the ASLLVD data.  But in the continuous signing data, what shows up as the last handshape is the SECOND handshape rather than the LAST one.

systematically, but one example:

<img width="766" alt="Screen Shot 2019-07-21 at 3 28 32 PM" src="https://user-images.githubusercontent.com/13629122/61596052-884df800-abcc-11e9-8b4b-77902ae438ba.png">

**Comment by cneidle** [comment]
There are still issues from above that have not been resolved:

1)  Note that the two signers shown in the composite video are not displayed on the
page with the occurrences.  Instead one of those signers is listed twice.

<img width="1496" alt="Screen Shot 2020-01-14 at 9 41 21 AM" src="https://user-images.githubusercontent.com/13629122/72353443-186b8680-36b2-11ea-86f9-227119bbb54e.png">

Handshapes are still missing here:

<img width="743" alt="Screen Shot 2020-01-14 at 9 40 34 AM" src="https://user-images.githubusercontent.com/13629122/72353444-186b8680-36b2-11ea-82fe-8c9e22b42c4f.png">


A potentially related additional problem:  The "G" handshape is not displayed in the
canonical example for GRADUATE, and note that this sign is not returned by a search for handshape G at the start of the dominant hand, so the handshape may really be missing (rather than it just being a display issue):

<img width="814" alt="Screen Shot 2020-01-14 at 9 43 55 AM" src="https://user-images.githubusercontent.com/13629122/72353699-7ac48700-36b2-11ea-9dee-3675fbba7941.png">


thanks!

**Comment by kwasiopoku** [comment]
This has been resolved

**Comment by cneidle** [comment]
Thank you !
